<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * AttachmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttachmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttachmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attachments');
    }
}
