<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * DepartmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Departments');
    }
}
