<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * DiscussionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Discussions');
    }
}
