<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * DiscussionsStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionsStatus');
    }
}
