<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * DiscussionsReportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsReportsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsReportsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionsReports');
    }
}
