<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * DiscussionsCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussionsCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussionsCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussionsComments');
    }
}
