<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ExtraFieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraFieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraFieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraFields');
    }
}
