<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ExtraFieldsListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraFieldsListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraFieldsListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraFieldsList');
    }
}
