<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * PhasesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhasesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhasesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phases');
    }
}
