<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ProjectsCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsComments');
    }
}
