<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ProjectsTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsTypes');
    }
}
