<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ProjectsStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsStatus');
    }
}
