<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ProjectsReportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsReportsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsReportsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsReports');
    }
}
