<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * ProjectsPhasesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectsPhasesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectsPhasesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectsPhases');
    }
}
