<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksStatus');
    }
}
