<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksPriority');
    }
}
