<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksTypes');
    }
}
