<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksComments');
    }
}
