<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksGroups');
    }
}
