<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksLabelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksLabelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksLabelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TasksLabels');
    }
}
