<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TasksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tasks');
    }
}
