<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsComments');
    }
}
