<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketsReports extends BaseTicketsReports
{
    
  public static function addFiltersToQuery($q,$reports_id,$sf_user=false)
  {
    if($r = Doctrine_Core::getTable('TicketsReports')->find($reports_id))
    { 
      
      if(strlen($r->getDepartmentsId())>0)
      {
        $q->whereIn('t.departments_id',explode(',',$r->getDepartmentsId()));
      }
      
      if(strlen($r->getTicketsStatusId())>0)
      {
        $q->whereIn('t.tickets_status_id',explode(',',$r->getTicketsStatusId()));
      }
       
      if(strlen($r->getTicketsTypesId())>0)
      {
        $q->whereIn('t.tickets_types_id',explode(',',$r->getTicketsTypesId()));
      }
  
      if(strlen($r->getProjectsStatusId())>0)
      {
        $q->whereIn('p.projects_status_id',explode(',',$r->getProjectsStatusId()));
      }
       
      if(strlen($r->getProjectsTypeId())>0)
      {
        $q->whereIn('p.projects_types_id',explode(',',$r->getProjectsTypeId()));
      }
                
      if(strlen($r->getProjectsId())>0)
      {
        $q->whereIn('p.id',explode(',',$r->getProjectsId()));
      }
      
      $q->orderBy(' ts.sort_order, LTRIM(ts.name), LTRIM(p.name), LTRIM(t.name)');                                    
    }
                  
    return $q;  
  }
}
