<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tickets');
    }
}
