<?php
/**
*qdPM
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@qdPM.net so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade qdPM to newer
* versions in the future. If you wish to customize qdPM for your
* needs please refer to http://www.qdPM.net for more information.
*
* @copyright  Copyright (c) 2009  Sergey Kharchishin and Kym Romanets (http://www.qdpm.net)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php

/**
 * TicketsTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketsTypes extends BaseTicketsTypes
{
  public static function getJsList()
  {
    $tickets_typess = Doctrine_Core::getTable('TicketsTypes')
      ->createQuery('a')
      ->orderBy('sort_order, name')
      ->execute();
      
    $html = '
      <script>
        var tickets_types_list = new Array();
        var tickets_types_by_sort_order = new Array();
        var default_tickets_types_id = 0;
    ';  
    
    foreach($tickets_typess as $v)
    {
      $html .= 'tickets_types_list[' . $v->getId() .']="' . addslashes($v->getName()) . '";' . "\n";
      
      if($v->getDefaultValue()==1)
      {
        $html .= 'default_tickets_types_id=' . $v->getId() . ";\n";
      }      
    }
    
    $html .= "\n\n";
    
    $i=0;
    foreach($tickets_typess as $v)
    {
      $html .= 'tickets_types_by_sort_order[' . $i .']="' . $v->getId() . '";' . "\n";
      $i++; 
    }
  
    $html .= '</script>';
    
    return $html;
  }
}
