<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TicketsTypes extends BaseTicketsTypes
{
  public static function getJsList()
  {
    $tickets_typess = Doctrine_Core::getTable('TicketsTypes')
      ->createQuery('a')
      ->orderBy('sort_order, name')
      ->execute();
      
    $html = '
      <script>
        var tickets_types_list = new Array();
        var tickets_types_by_sort_order = new Array();
        var default_tickets_types_id = 0;
    ';  
    
    foreach($tickets_typess as $v)
    {
      $html .= 'tickets_types_list[' . $v->getId() .']="' . addslashes($v->getName()) . '";' . "\n";
      
      if($v->getDefaultValue()==1)
      {
        $html .= 'default_tickets_types_id=' . $v->getId() . ";\n";
      }      
    }
    
    $html .= "\n\n";
    
    $i=0;
    foreach($tickets_typess as $v)
    {
      $html .= 'tickets_types_by_sort_order[' . $i .']="' . $v->getId() . '";' . "\n";
      $i++; 
    }
  
    $html .= '</script>';
    
    return $html;
  }
}
