<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsStatus');
    }
}
