<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsReportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsReportsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsReportsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsReports');
    }
}
