<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * TicketsTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketsTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketsTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketsTypes');
    }
}
