<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * UsersGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersGroups');
    }
}
