<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * VersionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VersionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VersionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Versions');
    }
}
