<?php
/**
* WORK SMART
*/
?>
<?php

/**
 * VersionsStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VersionsStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VersionsStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VersionsStatus');
    }
}
