<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/12/09 13:25:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm;host=localhost',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
