<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/12/09 07:26:46
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
