<?php
// auto-generated by sfSecurityConfigHandler
// date: 2022/12/09 07:25:38
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
