<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/12/09 07:38:16
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
