<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/12/09 07:32:32
sfConfig::add(array(
  'mod_discussionsstatus_enabled' => true,
  'mod_discussionsstatus_view_class' => 'sfPHP',
));
