<?php
/**
* WORK SMART
*/
?>
<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Attachments', 'doctrine');

/**
 * BaseAttachments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $bind_type
 * @property integer $bind_id
 * @property string $file
 * @property string $info
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method string      getBindType()  Returns the current record's "bind_type" value
 * @method integer     getBindId()    Returns the current record's "bind_id" value
 * @method string      getFile()      Returns the current record's "file" value
 * @method string      getInfo()      Returns the current record's "info" value
 * @method Attachments setId()        Sets the current record's "id" value
 * @method Attachments setBindType()  Sets the current record's "bind_type" value
 * @method Attachments setBindId()    Sets the current record's "bind_id" value
 * @method Attachments setFile()      Sets the current record's "file" value
 * @method Attachments setInfo()      Sets the current record's "info" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttachments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attachments');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bind_type', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('bind_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('info', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}
