<?php
/**
*qdPM
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@qdPM.net so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade qdPM to newer
* versions in the future. If you wish to customize qdPM for your
* needs please refer to http://www.qdPM.net for more information.
*
* @copyright  Copyright (c) 2009  Sergey Kharchishin and Kym Romanets (http://www.qdpm.net)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TicketsStatus', 'doctrine');

/**
 * BaseTicketsStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $group
 * @property integer $sort_order
 * @property integer $default_value
 * @property string $active
 * @property Doctrine_Collection $Tickets
 * @property Doctrine_Collection $TicketsComments
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getGroup()           Returns the current record's "group" value
 * @method integer             getSortOrder()       Returns the current record's "sort_order" value
 * @method integer             getDefaultValue()    Returns the current record's "default_value" value
 * @method string              getActive()          Returns the current record's "active" value
 * @method Doctrine_Collection getTickets()         Returns the current record's "Tickets" collection
 * @method Doctrine_Collection getTicketsComments() Returns the current record's "TicketsComments" collection
 * @method TicketsStatus       setId()              Sets the current record's "id" value
 * @method TicketsStatus       setName()            Sets the current record's "name" value
 * @method TicketsStatus       setGroup()           Sets the current record's "group" value
 * @method TicketsStatus       setSortOrder()       Sets the current record's "sort_order" value
 * @method TicketsStatus       setDefaultValue()    Sets the current record's "default_value" value
 * @method TicketsStatus       setActive()          Sets the current record's "active" value
 * @method TicketsStatus       setTickets()         Sets the current record's "Tickets" collection
 * @method TicketsStatus       setTicketsComments() Sets the current record's "TicketsComments" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicketsStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tickets_status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('group', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('default_value', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tickets', array(
             'local' => 'id',
             'foreign' => 'tickets_status_id'));

        $this->hasMany('TicketsComments', array(
             'local' => 'id',
             'foreign' => 'tickets_status_id'));
    }
}
